version: '3'

services:
  postgres_postgis:
    container_name: db
    build:
      context: .
    restart: always
    environment:
      POSTGRES_DB: postgis_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"